Support variables
IntelLabs/scenario_execution pull request #103
Opened 2024-06-28 07:24 UTC by fred-labs

Until now the final parameters of actions were generated during parsing.
To be able to support additional use cases, it is required to resolve just before execution.
With this PR the parsing is moved to a newly defined `execute()` method that is called with the actual execution of the behavior.

One use case is, that an action might change variables values for later usage. This is now possible by internally creating a py-trees blackboard variable for any `VariableDeclaration`.

Additionally it is now supported to refer to members of parameters (that can either be fixed parameters or variables). Example:

```
struct test_struct:
    member: string = "foo"

scenario test_scenario:
    do serial:
        log(test_struct.member)
```

2024-07-02 07:55 UTC, fmirus requested changes

2024-07-02 08:00 UTC, fred-labs commented on scenario_execution/scenario_execution/model/types.py
> +            ref = self.ref[0]
good spot. The check is already done during parsing.

2024-07-02 08:01 UTC, fred-labs commented on scenario_execution/scenario_execution/actions/base_action.py
> +    # def execute(self):
- because it differs for every action (depending on the osc-defined arguments). 
- because it's optional

2024-07-03 08:47 UTC, fmirus commented on scenario_execution/scenario_execution/model/types.py
> +        if isinstance(ref.ref, list) and isinstance(ref.ref[-1], MethodDeclaration):
do you check somewhere that ref.ref is not empty before using ref.ref[-1] in this statement?

2024-07-03 08:47 UTC, fmirus commented on scenario_execution/scenario_execution/model/types.py
> +            return self.ref[-1].get_type()
do you check somewhere that ref.ref is not empty before using ref.ref[-1] here?

2024-07-03 08:49 UTC, fred-labs commented on scenario_execution/scenario_execution/model/types.py
> +            return self.ref[-1].get_type()
yes. checks are done beforehand. Exception are captured. No need to add check

2024-07-03 08:50 UTC, fred-labs commented on scenario_execution/scenario_execution/model/types.py
> +        if isinstance(ref.ref, list) and isinstance(ref.ref[-1], MethodDeclaration):
same as other comment. exception are captured.

2024-07-03 08:50 UTC, fmirus approved these changes

2024-07-03 08:50 UTC, merged