create separate nav2 lib
IntelLabs/scenario_execution pull request #127
Opened 2024-07-26 13:22 UTC by fred-labs

### Description

### Pull request checklist

- [ ] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [ ] Format and Lint checks (`make check`) pass locally
- [ ] PR applies Apache 2.0 License to all code files

### Pull request type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe)

### Current behavior

### New behavior

### How to test

2024-07-26 15:38 UTC, fmirus approved these changes

2024-07-30 07:50 UTC, fmirus requested changes

2024-07-30 07:50 UTC, fmirus commented on libs/scenario_execution_nav2/README.md
> +# Scenario Execution Library for Gazebo
copy-paste leftover: Gazebo --> Nav2

2024-07-30 07:50 UTC, fmirus commented on libs/scenario_execution_nav2/package.xml
> +  <exec_depend>nav2_msgs</exec_depend>
don't we need tf2 and geometry_msgs here as well?

2024-07-30 07:57 UTC, fmirus approved these changes

2024-07-30 08:11 UTC, fred-labs commented on libs/scenario_execution_nav2/package.xml
> +  <exec_depend>nav2_msgs</exec_depend>
fixed

2024-07-30 08:11 UTC, fred-labs commented on libs/scenario_execution_nav2/README.md
> +# Scenario Execution Library for Gazebo
fixed

2024-07-30 08:14 UTC, merged