Moveit generic
IntelLabs/scenario_execution pull request #192
Opened 2024-09-17 15:04 UTC by Nikhil-Singhal-06

### Description

### Pull request checklist

- [ ] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [ ] Format and Lint checks (`make check`) pass locally
- [ ] PR applies Apache 2.0 License to all code files

### Pull request type

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe)

### Current behavior

### New behavior

### How to test

2024-09-18 14:00 UTC, fmirus requested changes

2024-09-18 14:00 UTC, fmirus commented on simulation/gazebo/arm_sim_scenario/launch/sim_moveit_scenario_launch.py
> +# Copyright (C) 2024 Intel Corporation
could you please add an rviz-file to this package for easier testing/visualization?

2024-09-18 17:47 UTC, Nikhil-Singhal-06 commented on examples/example_moveit/example_moveit.osc
> +        wait elapsed(3s)
Not necessary, I just added for visualization.

2024-09-26 06:22 UTC, fred-labs requested changes

2024-09-26 06:22 UTC, fred-labs commented on .gitmodules
> +[submodule "dependencies/moveit_resources"]
to be able to submit to the ros debian repositories, we try to get rid of submodules. Is this available as debian package?

2024-09-26 06:22 UTC, fred-labs commented on examples/example_moveit/example_moveit.osc
> +        joint_pose: serial:
you should be able to get rid of the "serial". Just add "joint_pose:" in front of the action call

2024-09-26 06:22 UTC, fred-labs commented on libs/scenario_execution_moveit/package.xml
> +  <name>scenario_execution_moveit</name>
isn't it "moveit2"?

2024-09-26 10:27 UTC, Nikhil-Singhal-06 commented on libs/scenario_execution_moveit/package.xml
> +  <name>scenario_execution_moveit</name>
Yes the lib is called moveit2 but the debian packages are still ros-distor-moveit and moveit_msgs.

Should I still rename the lib?

2024-10-01 14:07 UTC, fred-labs requested changes

2024-10-01 14:07 UTC, fred-labs commented on examples/example_moveit2/example_moveit2.osc
> +    manipulator: arm with:
please do not use "keep". Instead use arm(arm_joints: ....., gripper_joints: ....)

2024-10-01 14:07 UTC, fred-labs commented on libs/scenario_execution_moveit2/scenario_execution_moveit2/lib_osc/moveit2.osc
> +actor arm inherits robot:
please add descriptions. Follow other osc library files (at least one line describing the action itself. and after each argument, add a description for that. Argument indentation of other files is 42 characters)

2024-10-01 14:07 UTC, fred-labs commented on simulation/gazebo/arm_sim_scenario/launch/moveit_launch.py
> +        # .planning_scene_monitor(publish_robot_description=True)
cleanup

2024-10-02 07:12 UTC, fred-labs requested changes

2024-10-02 07:12 UTC, fred-labs commented on libs/scenario_execution_moveit2/scenario_execution_moveit2/lib_osc/moveit2.osc
> +import osc.standard.base
please add to docs/libraries.rst

2024-10-07 11:12 UTC, fred-labs requested changes

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +``arm``
please add heading "Actors".

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
reduce line-characters to match text

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +Use Moveit2 to move the arm joints to specified joint positions.
please clarify which action is called. Is there some additional documentation available?

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +     - If true, the action returns an executable plan in the response but does not attempt execution
is the action really returning the plan? where is it stored?

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +     - Scaling factors for optionally reducing the maximum joint velocities
false seems like an invalid value.

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +     - end effector pose to move to ``[x, y, z, quatx, quaty, quatz, w]``
please use pose_3d

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +     - If true, the action returns an executable plan in the response but does not attempt execution
same as above

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +     - ``false``
same as above

2024-10-07 11:12 UTC, fred-labs commented on docs/libraries.rst
> +     - ``move_action``
is this really the same name as for the other action?!

2024-10-07 11:39 UTC, Nikhil-Singhal-06 commented on docs/libraries.rst
> +     - ``move_action``
yes

2024-10-07 11:41 UTC, Nikhil-Singhal-06 commented on docs/libraries.rst
> +     - If true, the action returns an executable plan in the response but does not attempt execution
yes, it returns the plan as action response. as stated here 

https://docs.ros.org/en/melodic/api/moveit_msgs/html/msg/PlanningOptions.html

2024-10-07 12:48 UTC, fred-labs commented on docs/libraries.rst
> +     - If true, the action returns an executable plan in the response but does not attempt execution
from a scenario point of view, there is no returned value. right?

2024-10-07 12:54 UTC, Nikhil-Singhal-06 commented on docs/libraries.rst
> +     - If true, the action returns an executable plan in the response but does not attempt execution
right, if the target position is valid then scenario will return success. Also one can visualize the planning in Rviz, the arm shadow will follow the path but arm will not get executed (actual position will not change).

2024-10-07 13:12 UTC, fred-labs commented on docs/libraries.rst
> +     - If true, the action returns an executable plan in the response but does not attempt execution
then something like this should describe it better (feel free to improve)
If true, the plan is not executed after calculation. Calculated plan can be visualized in rviz.

2024-10-07 13:13 UTC, Nikhil-Singhal-06 commented on docs/libraries.rst
> +     - If true, the action returns an executable plan in the response but does not attempt execution
Sure

2024-10-07 14:49 UTC, fred-labs requested changes

2024-10-07 14:49 UTC, fred-labs commented on docs/libraries.rst
> +^^^^^^^
wrong section type. use """"""""" instead

2024-10-07 14:49 UTC, fred-labs commented on docs/libraries.rst
> +Use MoveIt2 to move the arm joints to specified joint positions, utilizing `MoveGroup action <https://docs.ros.org/en/noetic/api/moveit_msgs/html/action/MoveGroup.html>`__ from the move_group node ()
is there a non-rosdistro-specific link? noetic seems rather old

2024-10-07 14:49 UTC, fred-labs commented on docs/libraries.rst
> +Use MoveIt2 to move the arm joints to specified joint positions, utilizing `MoveGroup action <https://docs.ros.org/en/noetic/api/moveit_msgs/html/action/MoveGroup.html>`__ from the move_group node ()
what does "()" mean?

2024-10-07 14:49 UTC, fred-labs commented on docs/libraries.rst
> +     - end effector pose to move to ``[x, y, z, quatx, quaty, quatz, w]``
invalid description

2024-10-07 14:49 UTC, fred-labs commented on examples/example_moveit2/example_moveit2.osc
> +                goal_pose: ['-2.82', '+1.01', '-2.40', '-1.46', '0.57', '2.47', '0.0'],
use pose_3d.

pose_3d(position_3d(-2.82, 1.01, -2.4), orientation_3d(roll, pitch, yaw))

2024-10-07 14:49 UTC, fred-labs commented on examples/example_moveit2/example_moveit2.osc
> +                goal_pose: ['0.04'],
use numbers

2024-10-07 14:49 UTC, fred-labs commented on libs/scenario_execution_moveit2/scenario_execution_moveit2/lib_osc/moveit2.osc
> +    goal_pose: list of string            # list joint positions to move to
update

2024-10-07 14:49 UTC, fred-labs commented on simulation/gazebo/arm_sim_scenario/package.xml
> +  <description>Moveit2 Arm Simulation Scenario Execution</description>
MoveIt2

2024-10-07 14:51 UTC, Nikhil-Singhal-06 commented on examples/example_moveit2/example_moveit2.osc
> +                goal_pose: ['-2.82', '+1.01', '-2.40', '-1.46', '0.57', '2.47', '0.0'],
For joint to pose we cannot use pose3d as the values are the position of each joint and the list size can vary depending on number of joints.

2024-10-07 15:37 UTC, fred-labs commented on examples/example_moveit2/example_moveit2.osc
> +                goal_pose: ['-2.82', '+1.01', '-2.40', '-1.46', '0.57', '2.47', '0.0'],
got it.....but at least list of floats should be possible, right?

2024-10-08 14:23 UTC, fred-labs approved these changes

2024-10-08 14:28 UTC, fmirus approved these changes

2024-10-08 14:28 UTC, merged