fix-kubernetes-pod-status
IntelLabs/scenario_execution pull request #216
Opened 2024-10-18 11:27 UTC by Nikhil-Singhal-06

### Description
Pod status action fails to detect the pod status.

### Pull request checklist

- [] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [ ] Format and Lint checks (`make check`) pass locally
- [ ] PR applies Apache 2.0 License to all code files

### Pull request type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe)

### Current behavior

### New behavior

### How to test

2024-10-20 16:25 UTC, fred-labs requested changes

2024-10-20 16:25 UTC, fred-labs commented on libs/scenario_execution_kubernetes/scenario_execution_kubernetes/kubernetes_wait_for_pod_status.py
>          self.current_state = KubernetesWaitForPodStatusState.MONITORING
still needed?

2024-10-22 07:58 UTC, fmirus requested changes

2024-10-22 07:58 UTC, fmirus commented on libs/scenario_execution_kubernetes/scenario_execution_kubernetes/kubernetes_wait_for_pod_status.py
> +            # self.feedback_message = f"The pod '{self.target}' is currently in '{item[1].lower()}' status."  # pylint: disable= attribute-defined-outside-init
is this still needed? If not, remove

2024-10-22 12:06 UTC, fmirus submitted a review, later dismissed

2024-11-11 09:52 UTC, fred-labs requested changes

2024-11-11 09:52 UTC, fred-labs commented on libs/scenario_execution_kubernetes/scenario_execution_kubernetes/kubernetes_wait_for_pod_status.py
> +        self.monitoring_thread = threading.Thread(target=self.watch_pods, daemon=True)
this creates a new thread for every execution. Instead please rework the previous solution
--> in update() when getting the last element from update_queue (line 58) , store the item in a member variable (e.g. self.current_state). This allows you to keep the state for another execution. Then you can rework the update() function: 
1. move the check within update() into a separate function.
2. update() should look something like that afterwards:

```
if self.update_queue().empty():
  if self.current_state is not None and check(self.current_state):
    return  SUCCESS
  return RUNNING
else:
  while not self.update_queue.empty():
    self.current_state = self.update_queue.get()
    if check(self.current_state):
      return SUCCESS
  return RUNNING
```

2024-11-11 09:52 UTC, fred-labs commented on libs/scenario_execution_kubernetes/scenario_execution_kubernetes/kubernetes_wait_for_pod_status.py
> +        self.is_pod = False
please remove (see comment below)

2024-11-20 06:55 UTC, fred-labs approved these changes

2024-11-20 06:55 UTC, merged

2024-11-20 06:55 UTC, fred-labs approved these changes