feature/random-functions
IntelLabs/scenario_execution pull request #217
Opened 2024-10-18 12:20 UTC by Nikhil-Singhal-06

### Description

random function for int and list of strings

### Pull request checklist

- [ ] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [ ] Format and Lint checks (`make check`) pass locally
- [ ] PR applies Apache 2.0 License to all code files

### Pull request type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe)

### Current behavior

### New behavior

### How to test

2024-10-20 16:21 UTC, fred-labs requested changes
please add test

2024-10-22 07:50 UTC, fmirus requested changes

2024-10-22 12:04 UTC, fmirus requested changes

2024-10-22 12:04 UTC, fmirus commented on scenario_execution/scenario_execution/external_methods/random.py
> +def get_random_list_element(elemets_list: list):
typo: elemets_list

2024-10-22 12:04 UTC, fmirus commented on scenario_execution/scenario_execution/external_methods/random.py
> +
too many blank lines

2024-10-24 14:18 UTC, fmirus approved these changes

2024-11-20 08:01 UTC, merged