add cleanup function to navigation actions
IntelLabs/scenario_execution pull request #34
Opened 2024-03-07 16:38 UTC by Nikhil-Singhal-06

# Issue number and link (if applicable)

Issue Number:

# Objective of pull request
Terminate running navigation if scenario shutdown.

# Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [x] Format and Lint checks (`make check`) pass locally
- [x] PR applies Apache 2.0 License to all code files

# Pull request type

Please check your PR type:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes
- [ ] Other (please describe)

# What is the current behavior?
running navigation not terminating if scenario terminates.

# What is the new behavior?
navigation terminates when scenario shutdown.

# How to test

# Supplemental information

2024-03-07 17:38 UTC, fred-labs requested changes

2024-03-07 17:38 UTC, fred-labs commented on scenario_execution/scenario_execution/actions/nav_to_pose.py
> +        nav = BasicNavigator()
have you tested this?
Is using the local `self.nav_to_pose_client` action client not working?

2024-03-08 16:06 UTC, Nikhil-Singhal-06 commented on scenario_execution/scenario_execution/actions/nav_to_pose.py
> +        nav = BasicNavigator()
Yes, I did. It is working.

However I didn't try using self.nav_to_pose_client

2024-03-09 06:27 UTC, fred-labs requested changes

2024-03-09 06:27 UTC, fred-labs commented on scenario_execution/scenario_execution/actions/nav_to_pose.py
> +        nav = BasicNavigator()
please make use of self.nav_to_pose_client

2024-03-12 09:21 UTC, Nikhil-Singhal-06 commented on scenario_execution/scenario_execution/actions/nav_to_pose.py
> +        nav = BasicNavigator()
Done

2024-03-13 11:35 UTC, fmirus approved these changes

2024-03-13 11:38 UTC, merged