scenario control optional output parameter
IntelLabs/scenario_execution pull request #45
Opened 2024-03-19 15:48 UTC by Nikhil-Singhal-06

# Issue number and link (if applicable)

Issue Number:

# Objective of pull request
optional parameter to scenario execution control to get test results and logs

# Pull request checklist

Your PR fulfills the following requirements:
- [ ] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [ ] Format and Lint checks (`make check`) pass locally
- [ ] PR applies Apache 2.0 License to all code files

# Pull request type

Please check your PR type:

- [x] Feature

# What is the current behavior?
No parameter option available for scenario execution control output

# What is the new behavior?
optional parameter output_dir can be passed with scenario execution control

# How to test

# Supplemental information

2024-03-19 16:08 UTC, fmirus approved these changes

2024-03-19 16:16 UTC, fred-labs requested changes

2024-03-19 16:16 UTC, fred-labs commented on scenario_execution_control/scenario_execution_control/scenario_execution_control_node.py
> +            self.output_directory = "-o " + self.get_parameter('output_directory').value
shouldn't that be in ros parameter format? "output_directory:=...."

2024-03-20 08:42 UTC, Nikhil-Singhal-06 commented on scenario_execution_control/scenario_execution_control/scenario_execution_control_node.py
> +            self.output_directory = "-o " + self.get_parameter('output_directory').value
No, because the scenario execution node accepts arguments as general command line argument.

2024-03-20 12:42 UTC, fred-labs approved these changes

2024-03-20 12:46 UTC, merged