Action: check topic frequency
IntelLabs/scenario_execution pull request #68
Opened 2024-03-28 12:33 UTC by Nikhil-Singhal-06

### Description
New action for checking specific topic frequency

### Pull request checklist

- [ ] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [x] Tests are part of the PR (for bug fixes / features)
- [x] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [x] Format and Lint checks (`make check`) pass locally
- [x] PR applies Apache 2.0 License to all code files

### Pull request type

- [x] Feature
- [x] Documentation changes

### Current behavior
No action available to check topic frequency

### New behavior
new action assert_topic_latency

### How to test

2024-04-05 12:13 UTC, fmirus requested changes

2024-04-05 12:13 UTC, fmirus commented on docs/libraries.rst
> +check for topic latency.
Imho, this description could be a little more detailed. Particularly, what this action is intended for.

2024-04-05 12:13 UTC, fmirus commented on scenario_execution_gazebo/scenario_execution_gazebo/actions/gazebo_wait_for_sim.py
> +        self.timeout_sec = 60
why a hard-coded timeout?

2024-04-05 12:13 UTC, fmirus commented on scenario_execution_ros/scenario_execution_ros/lib_osc/ros.osc
> +    comparison_operator: comparison_operator = comparison_operator!le # the comparision is done using the this operator
typo: the this

2024-04-05 13:16 UTC, fmirus requested changes

2024-04-05 13:16 UTC, fmirus commented on scenario_execution_ros/scenario_execution_ros/actions/assert_topic_latency.py
> +        else:
isn't this else preventing the node from actually processing the very first message it receives?

2024-04-05 13:50 UTC, Nikhil-Singhal-06 commented on scenario_execution_ros/scenario_execution_ros/actions/assert_topic_latency.py
> +        else:
Yes, but I don't think this has any effect on the behavior of the action.

2024-04-08 07:58 UTC, fred-labs requested changes

2024-04-08 07:58 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +    def test_success(self):
please add a failing test

2024-04-08 13:07 UTC, fred-labs requested changes

2024-04-08 13:07 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +    def test_success(self):
I previously missed that. This test is actually also a "failing" test, right? (only that the action exits with success).
Please also add a test that shows, that the action keeps running while a topic comes in correctly (e.g. for a few seconds).

2024-04-08 13:20 UTC, Nikhil-Singhal-06 commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +    def test_success(self):
I think that we are not at the same level in terms of understanding how action should work.

First,
What exactly is the failing case?
If the latency specified in the scenario exceeds the actual latency of the topic. 

If so, then the scenario will succeed or fail depending on whether fail_on_finish is true or false.

Secondly,
the action will continue running if the actual latency is less than the specified latency regardless fail_on_finish is true or false, correct?

is this correct or am I missing something?

2024-04-08 13:32 UTC, fred-labs requested changes

2024-04-08 13:32 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +    def test_success(self):
That's correct. So a "good case" would be something like this:

```
scenario test_assert_topic_latency:
    do parallel:
        serial:
            assert_topic_latency() with:
                keep(it.topic_name == '/bla')
                keep(it.latency == 1.5s)
            emit fail
        serial:
            wait elapsed(10s)
            emit end
```

2024-04-08 13:33 UTC, Nikhil-Singhal-06 commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +    def test_success(self):
Ok, perfect

2024-04-08 13:37 UTC, closed without merging