Action topic frequency
IntelLabs/scenario_execution pull request #72
Opened 2024-04-08 13:44 UTC by Nikhil-Singhal-06

### Description
New action for checking specific topic frequency

### Pull request checklist

- [ ] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [x] Tests are part of the PR (for bug fixes / features)
- [x] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [x] Format and Lint checks (`make check`) pass locally
- [x] PR applies Apache 2.0 License to all code files

### Pull request type

- [x] Feature
- [x] Documentation changes

### Current behavior
No action available to check topic frequency

### New behavior
new action assert_topic_latency

### How to test

2024-04-16 08:03 UTC, fred-labs requested changes

2024-04-16 08:03 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +# TODO:
please update TODOs

2024-04-16 08:03 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +        self.publishing_thread = threading.Thread(target=self.publish_messages, daemon=True) # TODO: use a timer
please update TODO

2024-04-16 12:04 UTC, fred-labs requested changes

2024-04-16 12:04 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +        self.publish_timer = threading.Timer(5, self.publish_messages)
please use self.node.create_timer()

2024-04-16 12:06 UTC, fred-labs requested changes

2024-04-16 12:06 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +
missing tests?

2024-04-16 15:04 UTC, fred-labs requested changes

2024-04-16 15:04 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +        while self.running:
no while loop. Instead, the timer should trigger publish_message

2024-04-16 15:23 UTC, fmirus commented on scenario_execution_ros/scenario_execution_ros/lib_osc/ros.osc
> +    wait_for_first_message: bool = true # start measuring with the first recieved message
@fred-labs would it make sense to add the option of allowing a certain amount of time to violate the expected latency? For instance, if the expected latency is only violated once and only by a tiny margin, the action would trigger. In some use-cases, that might not be the desired behavior. We could add something like a `tolerance_duration` (in seconds), which is by default set to 0, but could be set to a higher value when needed. What do you think?

2024-04-17 07:30 UTC, fred-labs commented on scenario_execution_ros/scenario_execution_ros/actions/assert_topic_latency.py
> +                    self.feedback_message = f'latency of the topic {self.topic_name} exceeds the given latency. Average latency: {self.average_latency}'  # pylint: disable= attribute-defined-outside-
yes. and please also "shrink" the message length to a minimum. E.g. remove "the topic"

2024-04-17 14:10 UTC, fmirus requested changes

2024-04-18 08:29 UTC, fred-labs commented on scenario_execution_ros/scenario_execution_ros/lib_osc/ros.osc
> +    wait_for_first_message: bool = true # start measuring with the first recieved message
I would suggest to add that once someone asks for it. For now you could "emulate" this behavior by setting a `rolling_average_count`.

2024-04-18 08:33 UTC, fred-labs commented on docs/libraries.rst
> +- ``comparison_operator: comparison_operator``: operator to compare latency time. (default: ``le``)
Doesn't the `assert` prefix makes that clear. You normally want to assure, that a latency is below (i.e. less-or-equal) a certain threshold, right?

2024-04-18 12:43 UTC, fred-labs requested changes

2024-04-18 12:48 UTC, fred-labs requested changes

2024-04-18 14:23 UTC, Nikhil-Singhal-06 commented on scenario_execution_ros/scenario_execution_ros/actions/assert_topic_latency.py
> +                if len(self.rolling_average_count_queue) == self.rolling_average_count:
But in this case, I think the average will not be based on the latest values, as we are multiplying it by previous average every time.

2024-04-19 05:53 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +                wait_for_first_message: false)
Any comment?

2024-04-19 06:21 UTC, Nikhil-Singhal-06 commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +                wait_for_first_message: false)
I've changed the name of the topic it subscribes to, the new topic isn't publishing any messages. 

To ensure the topic is available at the start, I've included the publisher above. This prevents the action from exiting directly with the error "No topic found."

2024-04-19 06:25 UTC, fmirus commented on scenario_execution_ros/scenario_execution_ros/actions/assert_topic_latency.py
> +                if len(self.rolling_average_count_queue) == self.rolling_average_count:
In mathematical terms, @fred-labs comment reads like this
$$\left\(\sum_{i=1}^{n-1} \frac{average_{i}}{n-1} \right\) \cdot (n-1) + \frac{average_{n}}{n} = \left\(\sum_{i=1}^{n} \frac{average_{i}}{n} \right\)$$
which is taking the latest values into account, isn't it?

2024-04-22 14:18 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +    def test_wait_for_first_message_false_topic_type(self):
I would name this test  "...invalid_topic_type".

 Do you also test "wrong_topic_type"? So e.g. std_msgs.msg.Uint32

2024-04-22 14:18 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +        self.assertFalse(self.scenario_execution_ros.process_results())
a succeeding test with wait-for-first-message is missing.

2024-04-22 14:18 UTC, fred-labs commented on scenario_execution_ros/scenario_execution_ros/actions/assert_topic_latency.py
> +                if len(self.rolling_average_count_queue) == self.rolling_average_count:
any update here?

2024-04-22 14:18 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +    def test_with_false_topic_type(self):
invalid_topic_type

2024-04-22 14:18 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +
Test with wrong topic type missing.

2024-04-23 06:04 UTC, fred-labs commented on scenario_execution_ros/test/test_assert_topic_latency.py
> +        self.assertFalse(self.scenario_execution_ros.process_results())
no. with correct topic type and wait-for-first-message ==True

2024-04-24 06:36 UTC, fred-labs approved these changes

2024-04-24 06:37 UTC, merged