Relative spawn
IntelLabs/scenario_execution pull request #87
Opened 2024-05-27 07:58 UTC by fmirus

### Description
Added action for spawning an object in front of a given tf frame in gazebo, supersedes #86 

### Pull request checklist

- [ ] [Issue](https://github.com/IntelLabs/scenario_execution/issues) created that explains the change and why it's needed
- [ ] Tests are part of the PR (for bug fixes / features)
- [ ] [Docs](https://intellabs.github.io/scenario_execution/) reviewed and added / updated if needed (for bug fixes / features)
- [x] Format and Lint checks (`make check`) pass locally
- [x] PR applies Apache 2.0 License to all code files

### Pull request type

- [x] Bugfix
- [x] Feature

### Current behavior
no action to spawn an object relative to a given tf-frame

### New behavior
action created for spawning an object relative to a given tf-frame

### How to test
```
ros2 launch tb4_sim_scenario sim_nav_scenario_launch.py scenario:=examples/example_simulation/scenarios/example_simulation_relative_spawn.osc
```

2024-06-20 13:59 UTC, fred-labs requested changes

2024-06-20 13:59 UTC, fred-labs commented on docs/libraries.rst
> +Spawn an actor relative to a given ``frame_id`` within simulation (at a specified ``distance`` in front of ``frame_id``) by using the ``model`` and ``namespace`` of the associated actor.
please remove "by using the ``model`` and ``namespace`` of the associated actor"

2024-06-20 13:59 UTC, fred-labs commented on docs/libraries.rst
> +``osc_object.relative_spawn()``
please add entry in alphabetical order

2024-06-20 13:59 UTC, fred-labs commented on examples/example_simulation/models/box.sdf
> +            <size>0.25 0.25 0.5</size>
why?

2024-06-20 13:59 UTC, fred-labs commented on scenario_execution/scenario_execution/lib_osc/helpers.osc
> +    def get_float(min_val: float, max_val: float, seed: int) -> float is external scenario_execution.external_methods.random.get_float()
please also default 0 here

2024-06-20 13:59 UTC, fred-labs commented on scenario_execution_gazebo/scenario_execution_gazebo/actions/gazebo_relative_spawn_actor.py
> +class GazeboRelativeSpawnActor(RunProcess):
looks like there are a lot of similarities to GazeboSpawnActor. Can we use it as base class.

2024-06-20 13:59 UTC, fred-labs commented on scenario_execution_gazebo/scenario_execution_gazebo/lib_osc/gazebo.osc
> +action osc_actor.relative_spawn:
alphabetical order

2024-06-20 13:59 UTC, fred-labs commented on scenario_execution_gazebo/scenario_execution_gazebo/lib_osc/gazebo.osc
> +    # Spawn a simulation entity at a position relative to the frame_id (at a specified distance in front of  frame_id), uses namespace of entity
remove ", uses namespace of entity"

2024-06-20 13:59 UTC, fred-labs commented on scenario_execution_gazebo/setup.py
> +            'osc_actor.relative_spawn = scenario_execution_gazebo.actions.gazebo_relative_spawn_actor:GazeboRelativeSpawnActor',
alphabetical order (at least starting with that order)

2024-06-20 13:59 UTC, fred-labs commented on scenario_execution_ros/scenario_execution_ros/actions/odometry_distance_traveled.py
> +    def __init__(self, name, associated_actor, distance: float, namespace_override: str):
update doc

2024-06-20 13:59 UTC, fred-labs commented on simulation/gazebo/test_scenario_execution_gazebo/scenarios/test_relative_spawn.osc
> +                        keep(it.reference_point.x == -1.5m)
please use "modern" approach (not "keep(it.")

2024-06-20 14:52 UTC, fmirus commented on scenario_execution_gazebo/scenario_execution_gazebo/actions/gazebo_relative_spawn_actor.py
> +class GazeboRelativeSpawnActor(RunProcess):
I agree, but I do not see how this could work as the base class requires the spawn pose as input argument

2024-06-21 09:58 UTC, fred-labs approved these changes

2024-06-21 10:02 UTC, merged